<URI> ::= <scheme> ":" <authority> <path> <queryUp>
<scheme> ::= "http" | "https" | "ftp" | "mailto" | "file" | "data" | "irc"
<authority> ::= "//" <mozdaUser> <host> <mozdaPort>
<queryUp> ::= <query> | ""
<mozdaUser> ::= "" | <userinfo> "@"
<mozdaPort> ::= "" | ":" <port>
<userinfo> ::= <username> ":" <password>
<username> ::= regex(\w+)
<password> ::= regex(\w+)
<host> ::= regex(\w+) "." | <host> "." regex(\w+)
<port> ::= ":" regex(\d{1,})
<path> ::= <validPathSymbols> | <path> "/" <path>
<validPathSymbols> ::= <validPathSymbolsSub> | <validPathSymbols> <validPathSymbolsSub>
<validPathSymbolsSub> ::= regex([a-zA-Z0-9$_@.&+\-!*"',]+) | "(" | ")"  | "%" <hex> <hex>
<tackaSlash> ::= "/" | "."
<hex> ::= regex([0-9a-fA-F]+)
<mozdaTekst> ::= regex(\w+) | ""
<mozdaSlash> ::= "" | "/" | "."
<keyValuePair> ::= regex(\w+) "=" regex(\w+)
<qDelim> ::= "&" | ";"
<query> ::= "?" <keyValuePair> | <query> <qDelim> <keyValuePair>