<URL> ::= "http" <mozdaS> "://" <host> | <URL> <path> | <queryURL> | <URL> "/"
<queryURL> ::= <URL> <path> <query> | <URL> "/" <query>
<host> ::= <hostBlok> "." <hostBlok> | <host> "." <hostBlok>
<hostBlok> ::= regex([A-Za-z_0-9]+)
<mozdaS> ::= "s" | ""
<path> ::= "/" <pathBlok> | <path> "/" <pathBlok>
<pathBlok> ::= regex([a-zA-Z_\-0-9.]+) | <pathBlok> <hex> | <pathBlok> <hex> <pathBlok>
<hex> ::= regex(%[0-9A-Fa-f]{2})
<query> ::= "?" <KVPair> | <query> "&" <KVPair>
<KVPair> ::= <key> | <key> "=" <value>
<key> ::= regex([a-zA-Z0-9_]+)
<value> ::= regex([a-zA-Z0-9_\-]+)