<URI> ::= <scheme> ":" <authority> <path> <query>
<scheme> ::= "http" | "https" | "ftp" | "mailto" | "file" | "data" | "irc"
<authority> ::= "//" <mozdaUser> <host> <mozdaPort>
<mozdaUser> ::= "" | <userinfo> "@"
<mozdaPort> ::= "" | ":" <port>
<userinfo> ::= <username> ":" <password>
<username> ::= regex(\w+)
<password> ::= regex(\w+)
<host> ::= regex(\w+) "." regex(\w+) | <host> "." regex(\w+)
<port> ::= ":" regex(\d{1,})
<path> ::= regex(\w+) "/" | <path> regex(\w+) "/"
<keyValuePair> ::= regex(\w+) "=" regex(\w+)
<qDelim> ::= "&" | ";"
<query> ::= "?" <keyValuePair> | <query> <qDelim> <keyValuePair>
